{
 "title": "Dashboard Busines",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "type",
    "label": "type",
    "query": "SELECT DISTINCT type FROM wood_order;"
   }
  ]
 },
 "panels": [
  {
   "title": "Stock Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(quantity) as quantity, type as type FROM stock WHERE type IN ( ${type} ) GROUP BY type LIMIT 50 "
    }
   ]
  },
  {
   "title": "Order Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(quantity) AS \"Order Quantity\", type AS \"type\" FROM wood_order\r\n WHERE type IN ( type ) and $__timeFilter(timestamp)  GROUP BY type LIMIT 50 "
    }
   ]
  },
  {
   "title": "Missing Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(honored) AS \"honored\", type FROM wood_order GROUP BY type LIMIT 50 "
    },
    {
     "rawSql": "SELECT SUM(quantity) AS \"ask\", type FROM wood_order GROUP BY type LIMIT 50 "
    }
   ]
  }
 ]
}