{
 "title": "Dashboard de monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service",
    "query": {
     "query": "label_values(jvm_cpu_count,service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage Lumbercamp",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service_name=\"lumbercamp\", jvm_memory_pool_name=\"Metaspace\"}",
       "legendFormat": "{{jvm_memory_type}}"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{service_name=\"lumbercamp\", jvm_memory_type=\"heap\"})",
       "legendFormat": "heap"
      }
     ]
    },
    {
     "title": "CPU Usage Lumbercamp",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_cpu_time_seconds_total{service_name=\"lumbercamp\"}[1m])",
       "legendFormat": "CPU top 1m"
      },
      {
       "expr": "rate(jvm_cpu_time_seconds_total{service_name=\"lumbercamp\"}[5m])",
       "legendFormat": "CPU top 5m"
      },
      {
       "expr": "rate(jvm_cpu_time_seconds_total{service_name=\"lumbercamp\"}[15m])",
       "legendFormat": "CPU top 5m"
      }
     ]
    }
   ]
  },
  {
   "title": "${service_name}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "service_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage ${service_name}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service_name=\"$service_name\", jvm_memory_pool_name=\"Metaspace\"}",
       "legendFormat": "{{jvm_memory_type}}"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{service_name=\"$service_name\", jvm_memory_type=\"heap\"})",
       "legendFormat": "heap"
      }
     ]
    },
    {
     "title": "CPU Usage ${service_name}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_cpu_time_seconds_total{service_name=\"${service_name}\"}[1m])",
       "legendFormat": "CPU top 1m"
      },
      {
       "expr": "rate(jvm_cpu_time_seconds_total{service_name=\"${service_name}\"}[5m])",
       "legendFormat": "CPU top 5m"
      },
      {
       "expr": "rate(jvm_cpu_time_seconds_total{service_name=\"${service_name}\"}[15m])",
       "legendFormat": "CPU top 5m"
      }
     ]
    }
   ]
  }
 ]
}